---
- hosts: localhost
  become: false
  connection: local
  gather_facts: False
  vars:
  tasks:
    - name: clean up a key if exists
      ec2_key:
        state: absent
        name: "{{ ssh_key_name }}"
        region: "{{ region }}"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"

    - name: clean up AWS ec2 instances
      amazon.aws.ec2:
        instance_ids: '{{ item }}'
        region: '{{ region }}'
        state: 'absent'
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
      with_items:
        - "{{ ec2_server_id }}"
        - "{{ ec2_client_id }}"

    - name: clean up security group
      amazon.aws.ec2_group:
        name: "bandwidth_tester_group"
        description: bandwidth_tester security group
        vpc_id: "{{vpc_id}}"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{ region }}"
        state: absent
      register: cleanup_sec_group
      retries: 20
      delay: 5
      until: cleanup_sec_group is not failed
